name: 🚀 Deploy React App a Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar código
        uses: actions/checkout@v3

      - name: 📦 Instalar dependencias y generar build
        run: |
          npm install
          npm run build

      - name: 🚚 Subir a Hostinger por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
